export const data = {
  player: {
    new: true,
    name: 'Unknown Player',
    remainingEnemies: 4,
    wave: 1,
    health: 100,
    maxHealth: 100,
    level: 1,
    exp: 0,
    nextLevel: 100,
    coins: 0,
    gems: 0,
    power: 1,
    inventoryMax: 9,
    vaultMax: 3,
    equippedHat: {},
    equippedShirt: {},
    equippedPants: {},
    equippedShoes: {},
    equippedMainHand: {},
    equippedOffHand: {},
  },
  currentWave: [],
  inventory: [],
  vault: [],
  depositedItems: [],
  gamblers: [],
  currentJackpot: [],
  wonItems: [],
};