export const normalEnemies = [
  {
    id: 'alien-bug',
    name: 'Alien Bug',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'alien-reaper',
    name: 'Alien Reaper',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'behold',
    name: 'Behold',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'ceiling-barnacle',
    name: 'Ceiling Barnacle',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'centaur',
    name: 'Centaur',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'corrupt-zombie',
    name: 'Corrupt Zombie',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'daemon-hunter',
    name: 'Daemon Hunter',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'demonic-minion',
    name: 'Demonic Minion',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'evil-gnome',
    name: 'Evil Gnome',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'eye-spider',
    name: 'Eye Spider',
    type: 'normal',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, 
 ]

 export let eliteEnemies = [
  {
    id: 'brute',
    name: 'Brute',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'cherry-golem',
    name: 'Cherry Golem',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'cloaked-horseman',
    name: 'Cloaked Horseman',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'cyclops',
    name: 'Cyclops',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'devil',
    name: 'Devil',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'djinn',
    name: 'Djinn',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'dinorex',
    name: 'Dinorex',
    type: 'elite',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, 
 ]

 export const bossEnemies = [
  {
    id: 'ancient-dragon',
    name: 'Ancient Dragon',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'anubis',
    name: 'Anubis',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'cursed-sphinx',
    name: 'Cursed Sphinx',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'diablo',
    name: 'Diablo',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'double-dragon',
    name: 'Double Dragon',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'drakkar-dragon',
    name: 'Drakkar Dragon',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  }, {
    id: 'unstable-comet',
    name: 'Unstable Comet',
    type: 'boss',
    damage: 1,
    maxHealth: 8,
    health: 8,
    deaths: 0,
  },
]