export const player = {
    new: true,
    name: 'Unknown Player',
    remainingEnemies: 4,
    wave: 1,
    location: '',
    health: 100,
    maxHealth: 100,
    level: 1,
    exp: 0,
    nextLevel: 100,
    coins: 0,
    gems: 0,
    power: 10,
    inventoryMax: 9,
    vaultMax: 3,
    inventory: [],
    vault: [],
    equippedHeadwear: {},
    equippedTorso: {},
    equippedBottoms: {},
    equippedFootwear: {},
    equippedRanged: {},
    equippedMelee: {},
};