export const player = {
    new: true,
    name: 'Unknown Player',
    remainingEnemies: 4,
    wave: 1,
    location: '',
    health: 100,
    maxHealth: 100,
    level: 1,
    exp: 0,
    nextLevel: 100,
    gold: 0,
    energy: 0,
    droplets: 0,
    ember: 0,
    minerals: 0,
    passivePower: 1,
    activePower: 1,
    shockChance: 0,
    rainChance: 0,
    igniteChance: 0,
    groundChance: 0,
    inventoryMax: 9,
    vaultMax: 3,
    inventory: [],
    vault: [],
    equippedHeadwear: {},
    equippedTorso: {},
    equippedBottoms: {},
    equippedFootwear: {},
    equippedRanged: {},
    equippedMelee: {},
};